Provided a correct content of server's init-script

diff --git a/templates/server.init.d.erb b/templates/server.init.d.erb
--- a/templates/server.init.d.erb
+++ b/templates/server.init.d.erb
@@ -1,1 +1,107 @@
-ababa
+#!/bin/sh
+# to support chkconfig on RedHat Enterprise Linux
+# chkconfig: 345 97 3
+# description: <%= server_type %> @ Sedue search engine.
+
+SEDUE_HOME=<%= sedue_home %>
+INSTANCE_NAME=<%= instance %>
+
+. $SEDUE_HOME/sedue-env.sh
+
+SERVNAME="<%= server_script_name %>"
+SERVDIR="$SEDUE_HOME/etc/serve/$INSTANCE_NAME"
+SERV="$SEDUE_HOME/bin/serve -s $SERVDIR"
+SLEEP_INTERVAL=<%= server_sleep_interval %>
+
+get_serv_pid() {
+    $SERV $SERVNAME stat >/dev/null
+    RETVAL=$?
+    if [ $RETVAL -eq 0 ]; then
+        pid=$($SERV $SERVNAME stat | awk -F '=' '{print $2}');
+    else
+        pid=-1
+        echo "ERROR: Failed to run serve command. Please start serve-supervise first."
+        exit 1
+    fi
+}
+
+start() {
+    get_serv_pid
+    if [ $pid -gt 0 ]; then
+        echo "ERROR: $SERVNAME already running: pid=$pid"
+        exit 1
+    fi
+    echo "Starting <%= server_type %> <%= server_name %>..."
+    $SERV $SERVNAME start
+    RETVAL=$?
+    if [ $RETVAL -ne 0 ]; then
+        echo "ERROR: Failed to run serve command"
+        exit 1
+    fi
+    echo "Waiting..."
+    for i in `seq 0 10`; do
+        get_serv_pid
+        if [ $pid -eq 0 ]; then
+            sleep $SLEEP_INTERVAL
+        fi
+    done
+    get_serv_pid
+    if [ $pid -eq 0 ]; then
+        echo "ERROR: Failed to start $SERVNAME"
+        exit 1
+    fi
+}
+
+stop() {
+    echo "Stopping <%= server_type %> <%= server_name %>..."
+    get_serv_pid
+    if [ $pid -gt 0 ]; then
+        $SERV $SERVNAME kill
+        RETVAL=$?
+        if [ $RETVAL -ne 0 ]; then
+            echo "ERROR: Failed to run serve command. serve-supervise already died?"
+            exit 1
+        fi
+        sleep $SLEEP_INTERVAL
+        for i in `seq 0 10`; do
+            get_serv_pid
+            if [ $pid -gt 0 ]; then
+                sleep $SLEEP_INTERVAL
+            fi
+        done
+        if [ $pid -gt 0 ]; then
+            echo "ERROR: Failed to stop $SERVNAME"
+            exit 1
+        fi
+    else
+        echo "$SERVNAME already stopped."
+    fi
+}
+
+status() {
+    get_serv_pid
+    if [ $pid -gt 0 ]; then
+        echo "$SERVNAME is running: pid=$pid";
+    else
+        echo "$SERVNAME already stopped."
+    fi
+}
+
+case "$1" in
+    start)
+        start
+        ;;
+    stop)
+        stop
+        ;;
+    restart)
+        stop
+        start
+        ;;
+    status)
+        status
+        ;;
+    *)
+echo "Usage: `basename $0` {start|stop|restart|status}"
+        exit 1
+esac
